sudo: false

language: rust
rust:
  - stable
  - beta
  - nightly

cache: cargo

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - rustc --version
  - cargo --version
  - cargo build --verbose --all
